Possible fix

diff --git a/carbs b/carbs
--- a/carbs
+++ b/carbs
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 #Default Values
 export WALLPAPER=${WALLPAPER-TRUE}
@@ -133,13 +133,15 @@ then
 		cd yay
 		makepkg -si
 	fi
-	if [ $(pacman -T i3-wm) != "i3-wm" ]
+	if [ "$(pacman -Q i3-wm | awk '{print $1}')" = "i3-wm" ]
 	then	
 		sudo pacman -R i3-wm || errorhandler "Could not remove i3-wm"
 	fi
-	yay -T clipit ttf-material-icons-git | yay -S -
-	sudo $pacman i3-gaps dunst polkit-gnome ttf-bitstream-vera ttf-dejavu ttf-droid ttf-inconsolata ttf-indic-otf ttf-liberation entr xautolock compton terminator feh mpd xorg-xbacklight | xargs -r sudo pacman -S --noconfirm| tee -a $CARBHOME/.log && yay -T polybar | yay -S - && echo -e "${GREEN}Installed Mandatory Packages" | tee -a $CARBHOME/.log || errorhandler "Could not install some of the packages, check the logs at $CARBHOME/.log for more information"
-	yay -T i3lock-fancy-git | xargs -r yay -S || errorhandler "Could not install i3lock-fancy-git"
+	yay -T clipit ttf-material-icons-git | xargs -r yay -S --noconfirm
+	pacman -T i3-gaps dunst polkit-gnome ttf-bitstream-vera ttf-dejavu ttf-droid ttf-inconsolata ttf-indic-otf ttf-liberation entr xautolock compton terminator feh mpd xorg-xbacklight | xargs -r sudo pacman -S --noconfirm | tee -a $CARBHOME/.log || errorhandler "Could not install some of the packages, check the logs at $CARBHOME/.log for more information." 
+        yay -T polybar | xargs -r yay -S --noconfirm || errorhandler "Could not install polybar"
+	yay -T i3lock-fancy-git | xargs -r yay -S --noconfirm || errorhandler "Could not install i3lock-fancy-git"
+	echo -e "${GREEN}Installed Mandatory Packages" | tee -a $CARBHOME/.log 
 	sleep 2
 	printf "Downloading configuration files\n" | tee -a $CARBHOME/.log
 	cd $CARBHOME && git clone https://gitlab.cemkeylan.com/cemkeylan/dotfiles.git && cd $CARBHOME/dotfiles && mkdir -p $HOME/.config/i3 && mkdir -p $HOME/.config/polybar && mkdir -p $HOME/.config/terminator &&\
@@ -274,7 +276,7 @@ then
 		case $answer in
 			1)
 				echo Installing lf | tee -a $CARBHOME/.log
-				yay -T lf | yay -S - && echo -e "${GREEN}Installed successfully" | tee -a $CARBHOME/.log || errorhandler "Could not install lf"
+				yay -T lf | xargs -r yay -S --noconfirm && echo -e "${GREEN}Installed successfully" | tee -a $CARBHOME/.log || errorhandler "Could not install lf"
 				printf "\n# File Manager \nset \$fm terminator -e \"lf && exit\"\n" >> $HOME/.config/i3/config
 				break
 				;;
